---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.module"
  - "**.php"
exclude_paths: []
