#!/usr/bin/env php
<?php

require __DIR__ . '/app/bootstrap.php';

$cli = new \Commando\Command();

$cli->option('m')
	->aka('migration')
	->describedAs('When set, run the following migration. Format: `MigrationName:up/down`.');

if ( isset($cli['m']) && ! empty($cli['m']) ) {
	$migration_properties = explode(':', $cli['m']);

	$migration_class_name = '\\Lchski\\Migrations\\' . $migration_properties[0] . 'Migration';
	$migration_class = new $migration_class_name;

	call_user_func(array($migration_class, $migration_properties[1]));

	echo "Migration $migration_properties[0], in direction $migration_properties[1], run!";
}
