#!/usr/bin/env php
<?php

require __DIR__ . '/app/bootstrap.php';

$cli = new \Commando\Command();

$cli->option('m')
	->aka('migration')
	->describedAs('When set, run the following migration. Format: `MigrationName:up/down`.');

if ( isset($cli['m']) && ! empty($cli['m']) ) {
	$migration_properties = explode(':', $cli['m']);

	call_user_func(array('\\Lchski\\Migrations\\' . $migration_properties[0] . 'Migration', $migration_properties[1]));

	echo "Migration $migration_properties[0], in direction $migration_properties[1], run!";
}
